version: '3.2'
services:

  # ICUBAM service
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: icubam
    container_name: icubam-server
    command: ./start_server.sh
    restart: unless-stopped
    tty: true
    ports:
      - "8888:8888"
    working_dir: /home/icubam
    volumes:
      - type: bind
        source: ./resources/icubam-docker.env
        target: /home/icubam/resources/icubam.env
      - type: bind
        source: ./resources/icubam-docker.toml
        target: /home/icubam/resources/icubam.toml
      - type: bind
        source: ./resources/icubam.db
        target: /home/icubam/resources/icubam.db
      - type: bind
        source: ./resources/token.pickle
        target: /home/icubam/resources/token.pickle
    networks:
      - icubam-network

  # ICUBAM sms service
  app-sms:
    build:
      context: .
      dockerfile: Dockerfile
    image: icubam
    container_name: icubam-sms-server
    command: ./start_server_sms.sh
    restart: unless-stopped
    tty: true
    working_dir: /home/icubam
    volumes:
      - type: bind
        source: ./resources/icubam-docker.env
        target: /home/icubam/resources/icubam.env
      - type: bind
        source: ./resources/icubam-docker.toml
        target: /home/icubam/resources/icubam.toml
      - type: bind
        source: ./resources/icubam.db
        target: /home/icubam/resources/icubam.db
      - type: bind
        source: ./resources/token.pickle
        target: /home/icubam/resources/token.pickle
    networks:
      - icubam-network

  #Nginx Service
  app-nginx:
    image: nginx:alpine
    container_name: icubam-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - icubam-network
    volumes:
      - ./configs/nginx:/etc/nginx/conf.d
      - ./configs/certbot/conf:/etc/letsencrypt
      - ./configs/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./configs/certbot/conf:/etc/letsencrypt
      - ./configs/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

# Docker Networks
networks:
  icubam-network:
    driver: bridge