name: icubam
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - absl-py==0.9.0
  - conda-build==3.18.11
  - google-api-python-client==1.8.0
  - google-auth-httplib2==0.0.3
  - google-auth-oauthlib==0.4.1
  - pandas==1.0.3
  - pip==20.0.2
  - PyJWT==1.7.1
  - python-dotenv==0.12.0
  - tornado==6.0.3
  - toml==0.10.0
  - twilio==6.37.0
  - pip:
    - nexmo==2.4.0
    - messagebird==1.5.0
    - dotmap==1.3.1
