# Keys
title = "My TOML Config"

# Tables
[sms]
  [sms.dev]
  origin = "ICUBAM"
  carrier = "FAKE"
  [sms.prod]
  origin = "ICUBAM"
  carrier = "TW"

[db]
sqlite_path = "test.db"

[server]
  [server.dev]
  PORT = 8888  # will be lower cased when reading.
  base_url = "https://localhost"
  [server.prod]
  port = 443
  base_url = "https://test.icubam.net/"

[scheduler]
  [scheduler.prod]
  max_retries = 3
  [scheduler.dev]
  max_retries = 1
