version: '3.2'
services:

  # ICUBAM service
  app-server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: icubam
    container_name: icubam-server
    command: ./start_server.sh
    restart: unless-stopped
    tty: true
    ports:
      - "8888:8888"
    env_file:
      - ./docker/icubam-container.env
    environment:
      ENV_MODE : "dev"
    working_dir: /home/icubam
    volumes:
      - type: bind
        source: ./resources/config.toml
        target: /home/icubam/resources/config.toml
      - type: bind
        source: ./icubam.db
        target: /home/icubam/icubam.db
      - type: bind
        source: ./test.db
        target: /home/icubam/test.db
      - type: bind
        source: ./resources/token.pickle
        target: /home/icubam/resources/token.pickle
    networks:
      - icubam-network

  # ICUBAM sms service
  app-sms:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: icubam
    container_name: icubam-sms-server
    command: ./start_server_sms.sh
    restart: unless-stopped
    tty: true
    env_file:
      - ./docker/icubam-container.env
    environment:
      ENV_MODE : "dev"
    working_dir: /home/icubam
    volumes:
      - type: bind
        source: ./resources/config.toml
        target: /home/icubam/resources/config.toml
      - type: bind
        source: ./icubam.db
        target: /home/icubam/icubam.db
      - type: bind
        source: ./test.db
        target: /home/icubam/test.db
      - type: bind
        source: ./resources/token.pickle
        target: /home/icubam/resources/token.pickle
    networks:
      - icubam-network

# Docker Networks
networks:
  icubam-network:
    driver: bridge
