name: Python package

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/marketplace/actions/setup-miniconda
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
         auto-update-conda: true
         activate-environment: anaconda-client-env
         python-version: 3.8
         auto-activate-base: false
    - shell: bash -l {0}
      run: |
        conda info
        python --version
    - name: Install package
      shell: bash -l {0}
      run: |
        which python
        pip --version
        pip install pytest
        pip install -e .
    - name: Test with pytest
      shell: bash -l {0}
      env:
        JWT_SECRET: faketest
      run: |
        set -x
        pytest
